/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.accountManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.AccountDirectory;

/**
 * Class for account management
 * 
 * @author Shreyas Purkar
 */
public class AccountMngWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AccountDirectory accountDirectory;
    
    /**
     * Creates new form AccountMngWorkArea
     */
    public AccountMngWorkArea(JPanel userProcessContainer) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        accountDirectory = new AccountDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrtAcc = new javax.swing.JButton();
        btnMngAcc = new javax.swing.JButton();

        btnCrtAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/icons/create.png"))); // NOI18N
        btnCrtAcc.setText("Create Account");
        btnCrtAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrtAccActionPerformed(evt);
            }
        });

        btnMngAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/icons/manage.png"))); // NOI18N
        btnMngAcc.setText("Manage Account");
        btnMngAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrtAcc)
                    .addComponent(btnMngAcc))
                .addContainerGap(635, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCrtAcc, btnMngAcc});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnCrtAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMngAcc)
                .addContainerGap(445, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to create account 
     * 
     * @param evt 
     */
    private void btnCrtAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrtAccActionPerformed
        CreateAccountJPanel panel = new CreateAccountJPanel(userProcessContainer, 
                accountDirectory);
        userProcessContainer.add("CreateAccountJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnCrtAccActionPerformed

    /**
     * Method to manage account
     * 
     * @param evt 
     */
    private void btnMngAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAccActionPerformed
        ManageAccountsJPanel panel = new ManageAccountsJPanel(userProcessContainer, 
                accountDirectory);
        userProcessContainer.add("ManageAccountsJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrtAcc;
    private javax.swing.JButton btnMngAcc;
    // End of variables declaration//GEN-END:variables
}
